[package]
name = "picoquic"
version = "0.1.0"
authors = ["Bastian Köcher <git@kchr.de>"]

[dependencies]
picoquic-sys = { path = "picoquic-sys" }
tokio-core = "0.1"
failure = "0.1"
failure_derive = "0.1"
libc = "0.1.12"
