[package]
name = "picoquic-sys"
version = "0.1.0"
authors = ["Bastian Köcher <git@kchr.de>"]
build = "build.rs"

[dependencies]
openssl-sys = "0.9"

[build-dependencies]
cmake = "0.1"
bindgen = "0.32"
